// front-end/vue-app/src/components/user/CreateUser.vue
<template>
  <div class="submitform">

    <div class="form-group">
      <label for="login">login</label>
      <input type="text" class="form-control" id="login" required v-model="user.login" name="login">
    </div>

    <div class="form-group">
      <label for="password">password</label>
      <input type="text" class="form-control" id="password" required v-model="user.password" name="password">
    </div>

    <div class="form-group">
      <label for="birthDate">birthDate</label>
      <input type="date" class="form-control" id="birthDate" required v-model="user.birthDate" name="birthDate">
    </div>

    <div class="form-group">
      <label for="information">information</label>
      <input type="text" class="form-control" id="information" required v-model="user.information" name="information">
    </div>

    <div class="form-group">
      <form action="">
        <input required v-model="user.gender" type="radio" name="gender" value="true"><label>Male</label><br>
        <input required v-model="user.gender" type="radio" name="gender" value="false"><label>Female</label><br>
      </form>
    </div>

    <div v-if="!validation">
      <div class="form-group">
        {{ response }}
      </div>
    </div>

    <button v-on:click="saveCustomer" class="btn btn-success">create</button>
  </div>
</template>

<script>

  export default {
    name: "CreateUser",
    data() {
      return {
        user: {
          login: "",
          password: "",
          gender: "",
          birthDate: "",
          information: "",
        },
        validation: true,
        response: [],
      };
    },
    methods: {
      /* eslint-disable no-console */
      saveCustomer() {
        var data = {
          login: this.user.login,
          password: this.user.password,
          gender: this.user.gender,
          birthDate: this.user.birthDate,
          information: this.user.information,
        };

        http
          .post("/user", data)
          .then(response => {
            console.log(response.data);
            this.$router.push('/Users');
          })
          .catch(e => {
            this.validation = false;
            this.response.push(e.response.data.message);
            console.log(e);
          });
      }
      /* eslint-enable no-console */
    }
  };
</script>

<style>
  .submitform {
    max-width: 300px;
    margin: auto;
  }
</style>

// front-end/angular6-client/src/app/create-user/create-user.component.ts
import { Component, OnInit } from '@angular/core';
import {User} from "../models/user.model";
import {UserListService} from "../user-list/user-list.service";

@Component({
  selector: 'app-create-user',
  templateUrl: './create-user.component.html',
  styleUrls: ['./create-user.component.css']
})
export class CreateUserComponent implements OnInit {

  user: User = new User();
  submitted = false;

  constructor(private userService: UserListService) { }

  ngOnInit() {
  }

  newUser(): void {
    this.submitted = false;
    this.user = new User();
  }

  save() {
    this.userService.addUser(this.user)
      .subscribe(data => console.log(data), error => console.log(error));
    this.user = new User();
  }

  onSubmit() {
    this.submitted = true;
    this.save();
  }

}

<h3>Create User</h3>
<div [hidden]="submitted" style="width: 300px;">
  <form (ngSubmit)="onSubmit()">

    <div class="form-group">
      <label for="login">Login</label>
      <input type="text" class="form-control" id="login" required [(ngModel)]="user.login" name="login">
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input type="text" class="form-control" id="password" required [(ngModel)]="user.password" name="password">
    </div>

    <div class="form-group">
      <label for="gender">Gender</label>
      <input type="text" class="form-control" id="gender" required [(ngModel)]="user.gender" name="gender">
    </div>

    <div class="form-group">
      <label for="birthDate">Birth date</label>
      <input type="text" class="form-control" id="birthDate" required [(ngModel)]="user.birthDate" name="birthDate">
    </div>

    <div class="form-group">
      <label for="information">Information</label>
      <input type="text" class="form-control" id="information" required [(ngModel)]="user.information" name="information">
    </div>

    <button type="submit" class="btn btn-success">Submit</button>
  </form>
</div>

<div [hidden]="!submitted">
  <h4>You submitted successfully!</h4>
  <button class="btn btn-success" (click)="newUser()">Add</button>
</div>
